### ISSUE TITLE
undefined method `configure' for Twitter:Module 

### ISSUE THREAD

**Issue by stevenkolstad** [sferik/twitter#194]
I am running Rails 3.1. After bundle update I get this...

```
 /Users/Sites/config/initializers/twitter.rb:1:in `<top (required)>': undefined method `configure' for Twitter:Module (NoMethodError)
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `block in load'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/engine.rb:555:in `block (2 levels) in <class:Engine>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/engine.rb:554:in `each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/engine.rb:554:in `block in <class:Engine>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `instance_exec'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `run'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `each'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `run_initializers'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/application.rb:92:in `initialize!'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/Sites/config/environment.rb:5:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `block in require'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /U
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/builder.rb:51:in `instance_eval'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/builder.rb:51:in `initialize'
    from /Users/Sites/config.ru:1:in `new'
    from /Users/Sites/config.ru:1:in `<main>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/builder.rb:40:in `eval'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/builder.rb:40:in `parse_file'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/server.rb:200:in `app'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/commands/server.rb:46:in `app'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/server.rb:301:in `wrapped_app'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/rack-1.3.3/lib/rack/server.rb:252:in `start
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/commands/server.rb:70:in `start'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/commands.rb:54:in `block in <top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/commands.rb:49:in `tap'
    from /usr/local/rvm/gems/ruby-1.9.2-p180@rails31/gems/railties-3.1.0/lib/rails/commands.rb:49:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by MdMunam** [comment]
not working with this
