### ISSUE TITLE
Error getting user timeline after upgrading to 4.0 (Twitter::Error::BadRequest: Bad Authentication data)

### ISSUE THREAD

**Issue by mikefrederick** [sferik/twitter#315]
Moving from 2.0 to 4.0, I now get an error when using the user_timeline call. I am not using any configurations with the gem, but I don't believe I should need to if I am just using the user_timeline method.

Stacktrace below.

```
1.9.3-p194 :001 > Twitter.user_timeline("mike_frederick")
Twitter::Error::BadRequest: Bad Authentication data
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/response/raise_error.rb:20:in `on_complete'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.4/lib/faraday/response.rb:9:in `block in call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.4/lib/faraday/response.rb:63:in `on_complete'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.4/lib/faraday/response.rb:8:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.4/lib/faraday/request/url_encoded.rb:14:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.4/lib/faraday/request/multipart.rb:13:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/request/multipart_with_file.rb:21:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/faraday-0.8.4/lib/faraday/connection.rb:226:in `run_request'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/client.rb:71:in `request'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/client.rb:36:in `get'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/api.rb:2278:in `collection_from_response'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/api.rb:2316:in `objects_from_response'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter/api.rb:1600:in `user_timeline'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/twitter-4.0.0/lib/twitter.rb:23:in `method_missing'
    from (irb):1
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'1.9.3-p194 :002 > exit
```

**Comment by joshuawatson** [comment]
I have just updated 4.8 to 5.5, but i'm getting this error, how to solve this.

 user.create_direct_message(15995981243, "thanks")

Twitter::Error::BadRequest: Bad Authentication data.
	vendor/bundle/ruby/1.9.1/gems/twitter-5.5.1/lib/twitter/rest/response/raise_error.rb:21:in `on_complete'
	vendor/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/response.rb:9:in `block in call'
	/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/response.rb:63:in `on_complete'
	vendor/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/response.rb:8:in `call'
	/vendor/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request/url_encoded.rb:14:in `call'
	vendor/bundle/ruby/1.9.1/gems/faraday-0.8.7/lib/faraday/request/multipart.rb:13:in `call'
