### ISSUE TITLE
Deprecation notice on method call

### ISSUE THREAD

**Issue by jc00ke** [sferik/twitter#642]
I'm seeing a `DEPRECATION` warning when accessing `user.screen_name`, which is confusing me since I'm not accessing it by `user[:screen_name]` like the message suggests.

Maybe I'm setting up the test `tweet` incorrectly, which is leading to this warning?

```ruby
let(:user) {
  Twitter::User.new(id: 123456, screen_name: "foo")
}

let(:user_mention) {
  Twitter::Entity::UserMention.new(name: "Foo", screen_name: user.screen_name)
}

let(:tweet) {
  Twitter::Tweet.new(id: 1234567, entities: {user_mentions: [user_mention]}, user: user.to_h)
}
```

```
[1] pry(#<IncomingTweetWorker>)> tweet
=> #<Twitter::Tweet id=1234567>

[2] pry(#<IncomingTweetWorker>)> tweet.user_mentions
=> [#<Twitter::Entity::UserMention:0x007f61a39a4c80
  @attrs=#<Twitter::Entity::UserMention:0x007f61a39a4ed8 @attrs={:name=>"Foo", :screen_name=>"foo"}>>]

[3] pry(#<IncomingTweetWorker>)> tweet.user_mentions.first
=> #<Twitter::Entity::UserMention:0x007f61a39a4c80
 @attrs=#<Twitter::Entity::UserMention:0x007f61a39a4ed8 @attrs={:name=>"Foo", :screen_name=>"foo"}>>

[4] pry(#<IncomingTweetWorker>)> tweet.user_mentions.first.screen_name
/home/jesse/.gem/ruby/2.1.5/gems/twitter-5.13.0/lib/twitter/base.rb:144:in `attr_falsey_or_empty?': [DEPRECATION] #[:screen_name] is deprecated. Use #screen_name to fetch the value.
/home/jesse/.gem/ruby/2.1.5/gems/twitter-5.13.0/lib/twitter/base.rb:144:in `attr_falsey_or_empty?': [DEPRECATION] #[:screen_name] is deprecated. Use #screen_name to fetch the value.
/home/jesse/.gem/ruby/2.1.5/gems/twitter-5.13.0/lib/twitter/base.rb:144:in `attr_falsey_or_empty?': [DEPRECATION] #[:screen_name] is deprecated. Use #screen_name to fetch the value.
/home/jesse/.gem/ruby/2.1.5/gems/twitter-5.13.0/lib/twitter/base.rb:144:in `attr_falsey_or_empty?': [DEPRECATION] #[:screen_name] is deprecated. Use #screen_name to fetch the value.
/home/jesse/.gem/ruby/2.1.5/gems/twitter-5.13.0/lib/twitter/base.rb:92:in `block in define_attribute_method': [DEPRECATION] #[:screen_name] is deprecated. Use #screen_name to fetch the value.
```

I guess my question is, should I be using method calls (`user.screen_name = "foo"`) instead of the hash params?

Thanks!

**Comment by sferik** [comment]
Hey Jesse,

The issue is that you’re not calling `to_h` on the `Twitter::Entity::UserMention` object when you construct the `Twitter::Tweet` (as you do with the `Twitter::User`).

```diff
-  Twitter::Tweet.new(id: 1234567, entities: {user_mentions: [user_mention]}, user: user.to_h)
+  Twitter::Tweet.new(id: 1234567, entities: {user_mentions: [user_mention.to_h]}, user: user.to_h)
```

Sorry it took me 9 months to get around to looking into this issue. I guess you found another way to suppress (or ignore) the warnings. Thanks for reporting this.

**Comment by jc00ke** [comment]
Hey Erik, no worries! I don't remember what I did to fix it. That project never shipped anyway :cry:
