### ISSUE TITLE
Twitter::Error: SSL_connect SYSCALL returned=5 errno=0 state=unknown state

### ISSUE THREAD

**Issue by opan** [sferik/twitter#734]
hi, i've got this error message on production

here is full trace 

```
Twitter::Error: SSL_connect SYSCALL returned=5 errno=0 state=unknown state
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/request.rb:37:in `rescue in perform'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/request.rb:32:in `perform'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/utils.rb:50:in `perform_request'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/utils.rb:64:in `perform_post_with_object'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/tweets.rb:158:in `update!'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/twitter-5.15.0/lib/twitter/rest/tweets.rb:128:in `update'
	from (irb):1
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/console.rb:90:in `start'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/console.rb:9:in `start'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/railties-4.1.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
	from /home/nodeslink/projects/nodeslink-scm/bin/rails:8:in `<top (required)>'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `block in load'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/nodeslink/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:241:in `load'
	from /home/nodeslink/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/nodeslink/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

here my rails and ruby version

```
Rails 4.1.4
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
```

this error only thrown in my production, but not local (development)
any suggestion to solve this error?

thanks

**Comment by stve** [comment]
What version of OpenSSL are you using?

```ruby
require 'openssl'
puts OpenSSL::OPENSSL_VERSION
```

**Comment by opan** [comment]
this my version "OpenSSL 1.0.1 14 Mar 2012"

**Comment by stve** [comment]
You might want to try updating to the latest (1.0.2d) to see if that resolves the issue. 

Do you consistently get this error or is it intermittent?

**Comment by opan** [comment]
sorry for late replay sir, yes i get this error consistently.
i'll try your suggestion 

thanks sir

**Comment by opan** [comment]
my problem solved sir.
