### ISSUE TITLE
Ratelimit error not being thrown

### ISSUE THREAD

**Issue by sqlninja** [sferik/twitter#936]
In the last few days I am no longer able to send DMs.
Just getting this error:
```
TypeError: no implicit conversion of Symbol into Integer
/Users/johnhenderson/.rvm/gems/ruby-2.5.0/bundler/gems/twitter-844818cad07c/lib/twitter/rest/direct_messages.rb:194:in '[]'
/Users/johnhenderson/.rvm/gems/ruby-2.5.0/bundler/gems/twitter-844818cad07c/lib/twitter/rest/direct_messages.rb:194:in 'create_direct_message_event'
```

This [line](https://github.com/sferik/twitter/blob/master/lib/twitter/rest/direct_messages.rb#L194) is breaking now because the [response](https://github.com/sferik/twitter/blob/master/lib/twitter/rest/direct_messages.rb#L214) is empty

I know definitively this was working on 2018-07-20, because I was able to database the DM id from previous sends...

**Comment by sqlninja** [comment]
I think may have been something going on with Twitter, as messages are going through again, so disregarding for now...

**Comment by sqlninja** [comment]
Turns out to be a similar issue as #934 
I have added more commentary on that issue

**Comment by sqlninja** [comment]
I'm poking this issue because it appears that the empty response could be related to a rate limit (we saw that we were limited via the web app), but the responses coming back from the gem were just empty, thus not throwing the TooManyRequests error.
