### ISSUE TITLE
Unable to suppress an error thrown in a thread

### ISSUE THREAD

**Issue by taxen** [sferik/twitter#945]
I have some trouble with an array input of ID for block function.

It seems when one ID is given, the return value whether or not it is valid can be handled in rescue in the main code. However, when an array is used, a thread handling an invalid ID throws an error in itself, interrupting the main code before the rescue in the main code handles it. Use of thread is the same result.

Here are the test codes.

```
def block(client,id)
	client.block( id, open_timeout: 10 )
end

Thread.abort_on_exception = true
begin
	threads = []
		ids = [abc, 0]
		ids.each do |id|
			threads << Thread.new do
				p block(client,id)
			end
		end
	threads.each(&:join)

rescue Twitter::Error::NotFound => error
  puts "User not found"
ensure
end
exit
```
where client is defined as usual, and abc is a valid twitter account ID in integer in the real code.

When executing the code, it throws the following error and stops.
```
#<Thread:0x0000000003471848@test.rb:39 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        11: from test.rb:40:in `block (2 levels) in <main>'
        10: from test.rb:24:in `block'
         9: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/users.rb:177:in `block'
         8: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:122:in `parallel_users_from_response'
         7: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/utils.rb:23:in `pmap'
         6: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/utils.rb:23:in `collect'
         5: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/utils.rb:23:in `block in pmap'
         4: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:123:in `block in parallel_users_from_response'
         3: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
         2: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:50:in `perform_request'
         1: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:39:in `perform'
C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body': User not found. (Twitter::Error::NotFound)
User not found
```

Or if I use array of IDs as option...
```
def block(client,id)
	client.block( id, open_timeout: 10 )
end

begin
	id = [abc, 0]
	p block(client,id)
rescue Twitter::Error::NotFound => error
  puts "User not found"
ensure
end
exit
```
a thread error interrupts the main code before it handles the error.
```
#<Thread:0x00000000037028a0@C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/utils.rb:25 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/utils.rb:25:in `block (2 levels) in pmap'
        4: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:123:in `block in parallel_users_from_response'
        3: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
        2: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/utils.rb:50:in `perform_request'
        1: from C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:39:in `perform'
C:/Ruby/lib/ruby/gems/2.5.0/gems/twitter-6.2.0/lib/twitter/rest/request.rb:81:in `fail_or_return_response_body': User not found. (Twitter::Error::NotFound)
User not found

```

Now, the following code, using single integer as option...
```
def block(client,id)
	client.block( id, open_timeout: 10 )
end

begin
	id = 0
	p block(client,id)
rescue Twitter::Error::NotFound => error
  puts "User not found"
ensure
end
exit
```
stops on the same error, but this time only rescue in main code catches it.
`User not found
`

How can I catch Twitter::Error::NotFound error when using array of ID or threads while suppressing the thread error?

**Comment by ashleyconnor** [comment]
You can set `Thread.report_on_exception = false` but this is probably not what you want.

See https://bugs.ruby-lang.org/issues/14143
