### ISSUE TITLE
Unable to activate twitter-7.0.0, because buftok-0.3.0 conflicts with buftok (~> 0.2.0), http-3.3.0 conflicts with http (~> 4.0) ( Gem::ConflictError)

### ISSUE THREAD

**Issue by grz8** [sferik/twitter#990]
Hello

I have some gem conflicts.

```
Traceback (most recent call last):
        2: from ./tweet:4:in `<main>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- twitter (LoadError)
        5: from ./tweet:4:in `<main>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
        2: from /usr/lib/ruby/2.7.0/rubygems.rb:209:in `try_activate'
        1: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
/usr/lib/ruby/2.7.0/rubygems/specification.rb:2245:in `raise_if_conflicts': Unable to activate twitter-7.0.0, because buftok-0.3.0 conflicts with buftok (~> 0.2.0), http-3.3.0 conflicts with http (~> 4.0) (Gem::ConflictError)
        6: from ./tweet:4:in `<main>'
        5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:161:in `rescue in require'
        3: from /usr/lib/ruby/2.7.0/rubygems.rb:208:in `try_activate'
        2: from /usr/lib/ruby/2.7.0/rubygems.rb:215:in `rescue in try_activate'
        1: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
/usr/lib/ruby/2.7.0/rubygems/specification.rb:2245:in `raise_if_conflicts': Unable to activate twitter-7.0.0, because buftok-0.3.0 conflicts with buftok (~> 0.2.0), http-3.3.0 conflicts with http (~> 4.0) (Gem::ConflictError)
```

OS: Ubuntu 20.10 amd64

ruby version

```
$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
```

gem version

```
$ gem --version
3.1.2
```

Local gems

```
$ gem list --local

*** LOCAL GEMS ***

addressable (2.7.0)
apache_log-parser (3.1.2)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
buftok (0.3.0, 0.2.0)
bundler (2.2.16, default: 2.1.4)
cgi (default: 0.1.0)
csv (default: 3.1.2)
date (default: 3.0.0)
dbm (default: 1.1.0)
delegate (default: 0.1.0)
did_you_mean (default: 1.4.0)
domain_name (0.5.20190701)
equalizer (0.0.11)
etc (default: 1.1.0)
fcntl (default: 1.0.0)
ffi (1.15.0)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
forwardable (default: 1.3.1)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.0)
http (4.4.1, 3.3.0)
http-cookie (1.0.3)
http-form_data (2.3.0)
http-parser (1.2.3)
http_parser.rb (0.6.0)
io-console (default: 0.5.6)
ipaddr (default: 1.2.2)
irb (default: 1.2.3)
json (default: 2.3.0)
logger (default: 1.4.2)
mastodon-api (2.0.0)
matrix (default: 0.2.0)
memoizable (0.4.2)
minitest (5.13.0)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
naught (1.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.1.1)
observer (default: 0.1.0)
oj (3.11.5)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
ostruct (default: 0.2.0)
power_assert (1.1.7)
prime (default: 0.1.1)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.6)
racc (default: 1.4.16)
rake (13.0.1)
rdoc (default: 6.2.1)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
reline (default: 0.1.3)
rexml (default: 3.2.3)
rss (default: 0.2.8)
sdbm (default: 1.0.0)
simple_oauth (0.3.1)
singleton (default: 0.1.0)
stringio (default: 0.1.0)
strscan (default: 1.0.3)
test-unit (3.3.5)
thread_safe (0.3.6)
timeout (default: 0.1.0)
tracer (default: 0.1.0)
twitter (7.0.0)
unf (0.1.4)
unf_ext (0.0.7.7)
uri (default: 0.10.0)
webrick (default: 1.6.0)
xmlrpc (0.3.0)
yaml (default: 0.1.0)
zlib (default: 1.1.0)
```

Regards

**Comment by grz8** [comment]
This is because I `require` mastodon-api wich need another version of http and buftok gems as dependency.
